sudo: false
language: node_js
node_js: '0.12'
install:
- NODE_ENV=development npm install
cache:
  directories:
  - node_modules
env:
- NODE_ENV=production
script:
- npm run eslint
branches:
  only:
    - master
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: WQyBjudA3b4jwta/FjD510/kOs08OhJDuJGKh6UFBF2o77aVga0w7jg3zTDsH/ptVAg94aKGJEd7bEl9caaQ4k8jCaSwRvoJ6+bK7kgu/V5GJwS1SD3HucYdSasFA2Wg5KxaebVwweX9lNvKaeiNLpaBC65p3LKlfI8J8qi8cViOUflPrQslNQDMgLRVvXECtRbGOQNZwNjPsou65goJwECEeuLLVeOf99Xmn8/a6EOD+UpWIWrbvTuw5bznJQEa696lvmqhX7NGpoKepjTrjkxxiaXmQdVBo8hC2gH13r4rRf+Y2qhiSNpPt8Vg+sFmOSjaXzje+s0wHSYD3lx9csbwOn4alVfkBneSJVvlRhsUlFC3NbxojqPyMukXY6BR6BUQO5siNJJWxdlUyvbDk8VRBjLSfa1Q/do1BbkzpV0FI9vlPuBTO3rv2XNK1kqK4L5bxGESKOMNwKZtvQA22oRStGZQgqVTeQDOAKKhGsbchHNUWuIAfEPITvI6Zg92dgTUX3apPLF61WNYLGqzLyKazESTLvVocrqZtix/lIcMQnlTwZbtMsPZtSgblBL+wQCw4fTPokDj0YUx+QED5MsrFmlTufkm4Oa0J3OZ3sbQXmMhPCXbve8GJbGj6zjoM7m9vT1DiAXRtnCUIPPmdX3O7h872mXDLEuq14P8i40=
  app:
    secure: gnSQLUu412rbtNnU13O8jiH4dlOk3Oq0wgTqkaWw+jtEbLz6O3QGit8LSWAALtGc+1DxNEOCar3m49FnV+euR+f8wH3JZwVG+aQ7jU7wg4LztrPKjiX2e3G1zXAqu1tWOcKXAEiPfQJ4jPW4vxSohzwzQkqNgtMdq5xYlC6owN7L1PM0n8hhds29Dzgx4ptL31auNSSFHQXgW9CNNIGEQgv6IVYrdGEOZ/VZdqoSc17HIXBZWkKsb/M00N/9c6l/gJFzP4QNh3gLPxoe4+WR5RfayxXcwlESVjtaIePa1dclrU/GEPoUwN9WnmOkPvf/Wua+yLw+9X3fOJQlQVl2PFmsOqBmEPxWfgs9KKv2+snch9oQZeeRqyac26qp9nQ1e8HtPAneYcKH9L5ggrPML5De+c/MJnU8J9Wg/htXMSiTmPetGQIhmu0xwswLBxnowqPDvOFVlqAqER9oZzpnggki2/bBY7D2KmyUzFjbjpBkVs4A5vI5LuE0wfQ/yprwvEOlTi1Koz5LLMcBmdiAerv85v9zj3X4FlFaIO+5okedKNrtZCyDJycue9SqLG8BfH/IxJY03D3/DXq1pHo1I9NXoo44BDRRFNDOQg40BwBdfq7PNRejS7RSoSePAwUNvygADVaNdBRHua6hJzz2xquL4tSskjWT1A+prkf2Wn8=
